### ISSUE TITLE
KeyError: 'tvmonitor' when training first 19 classes

### ISSUE THREAD

**Issue by Xlgd** [yangdb/RD-IOD#2]
Sorry to bother you again, after I downloaded the VOC2007 dataset and put it into the `data/` folder, I ran 
`python trainval_net_ori.py --dataset pascal_voc --net res50 --bs 3 --lr 0.001 --nw 2 --epochs 20 --cuda --save_dir model_save_dir/voc07_19`
 to train the model using the first 19 categories and then encountered **KeyError: 'tvmonitor'**. 
I read the code and found that it will use the `pascal_voc_incre` function in `lib/datasets/pascal_voc_incre.py` to process the datasets. This code 
`self._classes = ('__background__', 'aeroplane', 'bicycle', 'bird', 'boat',
                         'bottle', 'bus', 'car', 'cat', 'chair',
                         'cow', 'diningtable', 'dog', 'horse',
                         'motorbike', 'person', 'pottedplant',
                         'sheep', 'sofa', 'train')#, 'tvmonitor'` 
filters the categories so that it contains only the first 19 categories, but because the annotation still contains the `tv` category, it causes this error to occur. I think I am running it wrong, what should I pay attention to before I run it? Thank you very much!

My `data/` folder structure is:
`data/VOCdevkit2007/VOC2007/Annotations/*.xml`
`data/VOCdevkit2007/VOC2007/ImageSets/Main/*.txt`
`data/VOCdevkit2007/VOC2007/JPEGImages/*.jpg`

My environment is:
Pytorch 1.0.0
Python 3.6.13

**Comment by Xlgd** [comment]
Maybe I should filter ahead and use images and annotations that contain only the top 19 categories for training?

**Comment by yangdb** [comment]
Yes. You should select the images and annotations of the first 19 categories.
