### ISSUE TITLE
The mAP for 19+1 incremental training was only 65.23

### ISSUE THREAD

**Issue by Xlgd** [yangdb/RD-IOD#3]
I'm sorry to bother you. I divided the dataset as you suggested. '**data/VOCdevkit2007/VOC2007**' contains training images and annotations for the **first 19** categories only, I changed the ’.xml' file so that it doesn't contain the last category of information. '**data/VOCdevkit2007-1/VOC2007**' and '**data/VOCdevkit/2007-10-inc-one/inc- tvmonitor**' both contain training images and annotations for the last category ('**tv**') only, '**data/VOCdevkittest/VOC2007**' contains test images and annotations for all 20 categories.
I first trained with the first 19 categories to get the model 'faster_rcnn_1_20_3290.pth' 
( `python trainval_net_ori.py --dataset pascal_voc --net res50 --bs 3 --lr 0.001 --nw 2 --epochs 20 --cuda --save_dir model_save_dir/voc07_19 --use _tfb`), 
and then use this model and the last category for incremental training to get the model 'faster_rcnn_2_10_557.pth' 
(`python increment.py --dataset pascal_voc_07_incre --net res50 --bs 1 --lr 0.0001 --nw 2 --epochs 10 --cuda --save_dir model_save_dir/1_inc --load_model model_baseline/voc07_19/res50/pascal_voc/faster_rcnn_1_20_3290.pth - -use_tfb --s 2`),
and finally use the command: 
`python test_net_increment.py --load_dir model_save_dir/1_inc/res50/pascal_voc_07_incre/faster_rcnn_2_10_557.pth - -dataset pascal_voc_test --net res50 --cuda` 
performing the test and get the following results:
~~~~~~~~
AP for aeroplane = 0.6915
AP for bicycle = 0.7674
AP for bird = 0.7268
AP for boat = 0.5437
AP for bottle = 0.3491
AP for bus = 0.7591
AP for car = 0.8113
AP for cat = 0.7841
AP for chair = 0.3387
AP for cow = 0.8067
AP for diningtable = 0.5517
AP for dog = 0.7917
AP for horse = 0.8280
AP for motorbike = 0.7638
AP for person = 0.7193
AP for pottedplant = 0.3688
AP for sheep = 0.7071
AP for sofa = 0.4609
AP for train = 0.7334
AP for tvmonitor = 0.5433
Mean AP = 0.6523
~~~~~~~~
I think I got something wrong so I don't get the right result, can you give me some advice? Thanks a lot! Looking forward to your reply!

**Comment by yangdb** [comment]
How about the performance of the old model on the first 19 classes?

**Comment by Xlgd** [comment]
> How about the performance of the old model on the first 19 classes?

Thank you very much for your reply! I ran 'test_net.py' and tested the first 19 categories using model 'faster_rcnn_1_20_3290.pth'. 
(`python test_net.py --load_dir model_baseline/voc07_19/res50/pascal_voc/faster_rcnn_1_20_3290.pth --dataset pascal_voc --net res50 --cuda`).
The results are as follows:
```
AP for aeroplane = 0.7453
AP for bicycle = 0.7878
AP for bird = 0.7266
AP for boat = 0.5797
AP for bottle = 0.5470
AP for bus = 0.7707
AP for car = 0.8306
AP for cat = 0.8343
AP for chair = 0.4816
AP for cow = 0.8334
AP for diningtable = 0.6542
AP for dog = 0.8399
AP for horse = 0.8398
AP for motorbike = 0.7563
AP for person = 0.7753
AP for pottedplant = 0.4133
AP for sheep = 0.7383
AP for sofa = 0.6626
AP for train = 0.7837
Mean AP = 0.7158
```
I think the performance of this model is outstanding, is there something wrong with my dataset partitioning? Thank you very much!

**Comment by yangdb** [comment]
Please comment Lines 73-78 in lib/model/faster_rcnn.py .

**Comment by Xlgd** [comment]
Thank you very much! I will re-run the program immediately as you suggested.
